name: django-web
on:
  push:
    branches:
            - master #Nombre de la rama
jobs:
    build:
            runs-on: ubuntu-latest #Sistema operativo
            steps: #Tareas que realizara
                    - name: Comprobar repositorio
                      uses: actions/checkout@v2 #Comprobar el repositorio
                    
                    - name: Configurar e Instalar Python
                      uses: actions/setup-python@v2 #Configurar el entorno de Python
                      with:
                            python-version: '3.13' #Version de Python
                    
                    - name: Instalar dependencias
                      run: |
                        cd ejercicioTrackDevops1 #Entrar a la carpeta del proyecto
                        pip install -r requirements.txt #Instalar dependencias en el archivo requirements.txt